### ISSUE TITLE
How can I change the datasource link to my own Postgres database?

### ISSUE THREAD

**Issue by christ25442544** [pamelafox/rag-on-postgres#11]
I think it is in the docker-compose.yaml right here (maybe I'm wrong), Can I change it directly and do azd up?
![Uploading Screenshot 2567-05-21 at 14.05.16.png…]()

**Comment by pamelafox** [comment]
Are you trying to connect to an existing Azure Postgres database?

**Comment by christ25442544** [comment]
Initially, I attempted to connect to my own Postgres database. However, it's now acceptable to use the one generated by your code. Thank you!
